In [1]:
import numpy as np

In [3]:
R=np.array([[4,np.NaN,np.NaN,2,np.NaN],
          [np.NaN,5,np.NaN,3,np.NaN],
          [np.NaN,np.NaN,3,4,4],
          [5,2,1,2,np.NaN]])

In [5]:
num_users,num_items=R.shape
# 잠재요인의 차원 = K
k=3

In [10]:
np.random.seed(1)
P=np.random.normal(size=(num_users,k))
Q=np.random.normal(size=(num_items,k))

In [11]:
p=np.random.normal(scale=1./k,size=(num_users,k))
q=np.random.normal(scale=1./k,size=(num_items,k))

In [13]:
non_zeros=[(i,j,R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j]>0]
non_zeros

[(0, 0, 4.0),
 (0, 3, 2.0),
 (1, 1, 5.0),
 (1, 3, 3.0),
 (2, 2, 3.0),
 (2, 3, 4.0),
 (2, 4, 4.0),
 (3, 0, 5.0),
 (3, 1, 2.0),
 (3, 2, 1.0),
 (3, 3, 2.0)]

In [12]:
from sklearn.metrics import mean_squared_error

In [14]:
def get_rmse(R,P,Q,non_zeros):
    error=0
    #예측 R행렬 생성
    full_pred_matrix=np.dot(P,Q.T)
    
    #실제 R행렬에서 null이 아닌 값의 위치 인덱스를 추출해 RMSE계산
    x_non_zero_ind= [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind= [non_zero[1] for non_zero in non_zeros]
    mse=mean_squared_error(R[x_non_zero_ind,y_non_zero_ind],full_pred_matrix[x_non_zero_ind,y_non_zero_ind])
    rmse=np.sqrt(mse)
    
    return rmse

In [17]:
steps=1000
r_lambda=0.01
learning_rate=0.01

for step in range(steps):
    for i,j,r in non_zeros:
        # 오차항 구하기
        eij=r-np.dot(P[i,:],Q[j,:].T)
        # SGD업데이트
        P[i,:]=P[i,:]+learning_rate*(eij*Q[j,:]-r_lambda*P[i,:])
        Q[j,:]=Q[j,:]+learning_rate*(eij*P[i,:]-r_lambda*Q[j,:])
        rmse=get_rmse(R,P,Q,non_zeros)
        if (step%50)==0:
            print("#iteration step: ",step,"rmse: ",rmse)

#iteration step:  0 rmse:  0.01912223242782337
#iteration step:  0 rmse:  0.019230645872065417
#iteration step:  0 rmse:  0.01917003224296491
#iteration step:  0 rmse:  0.0191077036311128
#iteration step:  0 rmse:  0.019131754083250907
#iteration step:  0 rmse:  0.018893307754784053
#iteration step:  0 rmse:  0.01892699450867586
#iteration step:  0 rmse:  0.01859303559685515
#iteration step:  0 rmse:  0.018719016748888467
#iteration step:  0 rmse:  0.0187834900388034
#iteration step:  0 rmse:  0.019087467992119685
#iteration step:  50 rmse:  0.019163628937438868
#iteration step:  50 rmse:  0.019270173694091956
#iteration step:  50 rmse:  0.019208955088934134
#iteration step:  50 rmse:  0.01914712992216352
#iteration step:  50 rmse:  0.019170711034134643
#iteration step:  50 rmse:  0.018933251349745762
#iteration step:  50 rmse:  0.018967014416522716
#iteration step:  50 rmse:  0.01863189850683569
#iteration step:  50 rmse:  0.018758660700392747
#iteration step:  50 rmse:  0.018823163778925674
#iteration step:  50 rmse:  0.019127787814553585
#iteration step:  100 rmse:  0.019204986660794045
#iteration step:  100 rmse:  0.019309677832139664
#iteration step:  100 rmse:  0.019247858446405863
#iteration step:  100 rmse:  0.019186551166457684
#iteration step:  100 rmse:  0.019209669666782322
#iteration step:  100 rmse:  0.018973182071793538
#iteration step:  100 rmse:  0.019007020949220185
#iteration step:  100 rmse:  0.01867077359758723
#iteration step:  100 rmse:  0.018798308769235456
#iteration step:  100 rmse:  0.018862839683774252
#iteration step:  100 rmse:  0.019168080627825053
#iteration step:  150 rmse:  0.019246293970160176
#iteration step:  150 rmse:  0.0193491472104103
#iteration step:  150 rmse:  0.01928673127998769
#iteration step:  150 rmse:  0.019225955584476602
#iteration step:  150 rmse:  0.01924861833102999
#iteration step:  150 rmse:  0.01901308822923744
#iteration step:  150 rmse:  0.01904700236453915
#iteration step:  150 rmse:  0.018709649060891856
#iteration step:  150 rmse:  0.018837949084644638
#iteration step:  150 rmse:  0.018902505830835768
#iteration step:  150 rmse:  0.019208335004430286
#iteration step:  200 rmse:  0.019287537515435087
#iteration step:  200 rmse:  0.0193885690192157
#iteration step:  200 rmse:  0.019325560818530665
#iteration step:  200 rmse:  0.019265329678416925
#iteration step:  200 rmse:  0.01928754364592666
#iteration step:  200 rmse:  0.019052956399898947
#iteration step:  200 rmse:  0.01908694519355693
#iteration step:  200 rmse:  0.01874851133592538
#iteration step:  200 rmse:  0.01887756803063855
#iteration step:  200 rmse:  0.01894214856920143
#iteration step:  200 rmse:  0.019248537786890695
#iteration step:  250 rmse:  0.01932870235617564
#iteration step:  250 rmse:  0.01942792884638727
#iteration step:  250 rmse:  0.01936433268639746
#iteration step:  250 rmse:  0.01930465836316922
#iteration step:  250 rmse:  0.01932643063073851
#iteration step:  250 rmse:  0.019092771562573246
#iteration step:  250 rmse:  0.019126834372179654
#iteration step:  250 rmse:  0.018787345241445833
#iteration step:  250 rmse:  0.018917150378567796
#iteration step:  250 rmse:  0.01898175265121974
#iteration step:  250 rmse:  0.01928867421955725
#iteration step:  300 rmse:  0.019369772090579725
#iteration step:  300 rmse:  0.01946721080563519
#iteration step:  300 rmse:  0.019403031031703228
#iteration step:  300 rmse:  0.019343925094291534
#iteration step:  300 rmse:  0.019365262832990192
#iteration step:  300 rmse:  0.01913251722553481
#iteration step:  300 rmse:  0.01916665336968066
#iteration step:  300 rmse:  0.018826134105043104
#iteration step:  300 rmse:  0.018956679416638745
#iteration step:  300 rmse:  0.01902130136114102
#iteration step:  300 rmse:  0.019328728077361912
#iteration step:  350 rmse:  0.01941072898081009
#iteration step:  350 rmse:  0.019506397661263313
#iteration step:  350 rmse:  0.019441638650933398
#iteration step:  350 rmse:  0.019383111992390067
#iteration step:  350 rmse:  0.01940402245294999
#iteration step:  350 rmse:  0.019172175551476846
#iteration step:  350 rmse:  0.019206384313652857
#iteration step:  350 rmse:  0.018864859888850886
#iteration step:  350 rmse:  0.018996137075820627
#iteration step:  350 rmse:  0.019060776640158105
#iteration step:  350 rmse:  0.019368681790913538
#iteration step:  400 rmse:  0.019451554074306286
#iteration step:  400 rmse:  0.019545470948891946
#iteration step:  400 rmse:  0.01948013710958998
#iteration step:  400 rmse:  0.019422199963552333
#iteration step:  400 rmse:  0.01944269046420651
#iteration step:  400 rmse:  0.019211727478524808
#iteration step:  400 rmse:  0.019246008111014012
#iteration step:  400 rmse:  0.01890350331135848
#iteration step:  400 rmse:  0.01903550405178436
#iteration step:  400 rmse:  0.019100159207493427
#iteration step:  400 rmse:  0.019408516567598018
#iteration step:  450 rmse:  0.01949222732086486
#iteration step:  450 rmse:  0.019584411091978487
#iteration step:  450 rmse:  0.019518506858650902
#iteration step:  450 rmse:  0.019461168815619097
#iteration step:  450 rmse:  0.019481246730122147
#iteration step:  450 rmse:  0.01925115283710543
#iteration step:  450 rmse:  0.01928550456484807
#iteration step:  450 rmse:  0.01894204396510292
#iteration step:  450 rmse:  0.01907475992265518
#iteration step:  450 rmse:  0.019139428677313417
#iteration step:  450 rmse:  0.01944821250846632
#iteration step:  500 rmse:  0.019532727685392458
#iteration step:  500 rmse:  0.019623197514041773
#iteration step:  500 rmse:  0.01955672734675092
#iteration step:  500 rmse:  0.019499997370202818
#iteration step:  500 rmse:  0.019519670116068533
#iteration step:  500 rmse:  0.019290430462564692
#iteration step:  500 rmse:  0.019324852486978884
#iteration step:  500 rmse:  0.018980460430134193
#iteration step:  500 rmse:  0.019113883262479498
#iteration step:  500 rmse:  0.019178563671375812
#iteration step:  500 rmse:  0.01948774872081295
#iteration step:  550 rmse:  0.01957303325627962
#iteration step:  550 rmse:  0.019661808746545266
#iteration step:  550 rmse:  0.019594777128035052
#iteration step:  550 rmse:  0.01953866357039546
#iteration step:  550 rmse:  0.01955793859738478
#iteration step:  550 rmse:  0.01932953830348211
#iteration step:  550 rmse:  0.019364029806225543
#iteration step:  550 rmse:  0.01901873038320351
#iteration step:  550 rmse:  0.01915285175035875
#iteration step:  550 rmse:  0.019217541927358365
#iteration step:  550 rmse:  0.0195271034264091
#iteration step:  600 rmse:  0.019613121349394715
#iteration step:  600 rmse:  0.01970022253243537
#iteration step:  600 rmse:  0.01963263396567952
#iteration step:  600 rmse:  0.019577144584165707
#iteration step:  600 rmse:  0.019596029363057328
#iteration step:  600 rmse:  0.019368453525669956
#iteration step:  600 rmse:  0.019403013672326132
#iteration step:  600 rmse:  0.019056830702648585
#iteration step:  600 rmse:  0.019191642275231076
#iteration step:  600 rmse:  0.01925634040285588
#iteration step:  600 rmse:  0.01956625406536895
#iteration step:  650 rmse:  0.019652968607723805
#iteration step:  650 rmse:  0.019738415925366272
#iteration step:  650 rmse:  0.019670274931110947
#iteration step:  650 rmse:  0.019615416903468522
#iteration step:  650 rmse:  0.019633918915143187
#iteration step:  650 rmse:  0.01940715261188208
#iteration step:  650 rmse:  0.01944178055556023
#iteration step:  650 rmse:  0.019094737569009545
#iteration step:  650 rmse:  0.019230231036338294
#iteration step:  650 rmse:  0.019294935375076972
#iteration step:  650 rmse:  0.019605177395697188
#iteration step:  700 rmse:  0.019692551096678567
#iteration step:  700 rmse:  0.019776365384634776
#iteration step:  700 rmse:  0.019707676498947294
#iteration step:  700 rmse:  0.01965345643908884
#iteration step:  700 rmse:  0.01967158316395228
#iteration step:  700 rmse:  0.019445611457247408
#iteration step:  700 rmse:  0.019480306342083302
#iteration step:  700 rmse:  0.019132426561380294
#iteration step:  700 rmse:  0.019268593639387925
#iteration step:  700 rmse:  0.01933330253625639
#iteration step:  700 rmse:  0.019643849588527384
#iteration step:  750 rmse:  0.019731844395136297
#iteration step:  750 rmse:  0.019814046865887044
#iteration step:  750 rmse:  0.019744814637718273
#iteration step:  750 rmse:  0.01969123861127654
#iteration step:  750 rmse:  0.019708997519048754
#iteration step:  750 rmse:  0.019483805460485042
#iteration step:  750 rmse:  0.019518566425032125
#iteration step:  750 rmse:  0.019169872749547543
#iteration step:  750 rmse:  0.019306705188466007
#iteration step:  750 rmse:  0.019371417084837535
#iteration step:  750 rmse:  0.019682246319113965

#iteration step:  800 rmse:  0.019770823682247852
#iteration step:  800 rmse:  0.019851435907635804
#iteration step:  800 rmse:  0.019781664896405437
#iteration step:  800 rmse:  0.019728738436207684
#iteration step:  800 rmse:  0.019746136976099688
#iteration step:  800 rmse:  0.019521709610934145
#iteration step:  800 rmse:  0.019556535791436114
#iteration step:  800 rmse:  0.019207050781952867
#iteration step:  800 rmse:  0.019344540373740962
#iteration step:  800 rmse:  0.019409253812466443
#iteration step:  800 rmse:  0.019720342853622935
#iteration step:  850 rmse:  0.019809463820082637
#iteration step:  850 rmse:  0.019888507713656283
#iteration step:  850 rmse:  0.019818202486868764
#iteration step:  850 rmse:  0.019765930608341396
#iteration step:  850 rmse:  0.019782976199639722
#iteration step:  850 rmse:  0.019559298571460982
#iteration step:  850 rmse:  0.019594189104998133
#iteration step:  850 rmse:  0.019243934969531362
#iteration step:  850 rmse:  0.019382073555017396
#iteration step:  850 rmse:  0.01944678718685425
#iteration step:  850 rmse:  0.019758114131778703
#iteration step:  900 rmse:  0.019847739432158215
#iteration step:  900 rmse:  0.019925237231309824
#iteration step:  900 rmse:  0.019854402362206314
#iteration step:  900 rmse:  0.019802789578710588
#iteration step:  900 rmse:  0.019819489601786783
#iteration step:  900 rmse:  0.019596546757286427
#iteration step:  900 rmse:  0.01963150078478867
#iteration step:  900 rmse:  0.019280499365469633
#iteration step:  900 rmse:  0.019419278841183288
#iteration step:  900 rmse:  0.019483991430555545
#iteration step:  900 rmse:  0.01979553484542019
#iteration step:  950 rmse:  0.019885624977919517
#iteration step:  950 rmse:  0.019961599225857805
#iteration step:  950 rmse:  0.01989023929111154
#iteration step:  950 rmse:  0.019839289629215006
#iteration step:  950 rmse:  0.01985565141697574
#iteration step:  950 rmse:  0.019633428410798136
#iteration step:  950 rmse:  0.019668445079917486
#iteration step:  950 rmse:  0.0193167178409401
#iteration step:  950 rmse:  0.0194561301656139
#iteration step:  950 rmse:  0.01952084059572786
#iteration step:  950 rmse:  0.01983257951303002

In [19]:
np.round(np.dot(P,Q.T),3)

array([[ 3.992,  0.416,  1.603,  2.002,  2.12 ],
       [ 8.664,  4.98 ,  0.93 ,  2.979, -0.359],
       [ 5.942, -1.163,  2.988,  3.972,  3.991],
       [ 4.962,  2.012,  1.004,  2.029,  0.677]])

In [20]:
import pandas as pd

In [88]:
movies=pd.read_csv(r'C:\Users\PC\Desktop\새 폴더\tmdb_5000_movies.csv')
print(movies.shape)
movies.head(1)

(4803, 20)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [100]:
movies_df = movies[['id','title', 'genres', 'vote_average', 'vote_count',
                 'popularity', 'keywords', 'overview']]

In [101]:
from ast import literal_eval

movies_df['genres'] = movies_df['genres'].apply(literal_eval)
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)

<ipython-input-101-a1e109db40c7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['genres'] = movies_df['genres'].apply(literal_eval)
<ipython-input-101-a1e109db40c7>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)

In [102]:
movies_df['genres'] = movies_df['genres'].apply(lambda x : [ y['name'] for y in x])
movies_df['keywords'] = movies_df['keywords'].apply(lambda x : [ y['name'] for y in x])
movies_df[['genres', 'keywords']][:1]

<ipython-input-102-4193ab78f473>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['genres'] = movies_df['genres'].apply(lambda x : [ y['name'] for y in x])
<ipython-input-102-4193ab78f473>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['keywords'] = movies_df['keywords'].apply(lambda x : [ y['name'] for y in x])

,genres,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon..."

# 장르 콘텐츠 유사도 측정
- 장르 유사도가 높은 영화 중 평점이 높은 순으로 영화추천

In [103]:
from sklearn.feature_extraction.text import TfidfVectorizer
movies_df['genres_literal']=movies_df['genres'].apply(lambda x : (' ').join(x))
tfidf=TfidfVectorizer(min_df=0,ngram_range=(1,2))
genre_matrix=tfidf.fit_transform(movies_df['genres_literal'])

<ipython-input-103-4411506d051c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['genres_literal']=movies_df['genres'].apply(lambda x : (' ').join(x))

In [104]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_matrix, genre_matrix)
print(genre_sim.shape)
print(genre_sim[:2])

(4803, 4803)
[[1.         0.49309367 0.29270708 ... 0.         0.         0.        ]
 [0.49309367 1.         0.17786505 ... 0.         0.         0.        ]]

In [105]:
genre_sim_sorted_ind = genre_sim.argsort()[:, ::-1]
print(genre_sim_sorted_ind[:1])

[[   0   14   46 ... 3038 3037 2401]]

In [96]:
genre_sim_sorted_ind

array([[   0,   14,   46, ..., 3038, 3037, 2401],
       [ 329, 2390,  206, ..., 3069, 3067, 2401],
       [   2, 1740, 1542, ..., 3000, 2999, 2401],
       ...,
       [4800, 3809, 3285, ..., 2229, 2230,    0],
       [4802, 1594, 1596, ..., 3204, 3205,    0],
       [4802, 4710, 4521, ..., 3140, 3141,    0]], dtype=int64)

In [97]:
genre_sim_sorted_ind[0,0:3].reshape(-1)

array([ 0, 14, 46], dtype=int64)

In [106]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    
    # 인자로 입력된 movies_df DataFrame에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
    title_movie = df[df['title'] == title_name]
    
    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고 
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]
    
    # 추출된 top_n index들 출력. top_n index는 2차원 데이터 임. 
    #dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    
    return df.iloc[similar_indexes]

In [109]:
find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather',10)

[[1663 1243 4065 1464 2731 3887  892 1881 1370 3378]]

,id,title,genres,vote_average,vote_count,popularity,keywords,overview,genres_literal
1663,311,Once Upon a Time in America,"[Drama, Crime]",8.2,1069,49.336397,"[life and death, corruption, street gang, rape...",A former Prohibition-era Jewish gangster retur...,Drama Crime
1243,203,Mean Streets,"[Drama, Crime]",7.2,345,17.002096,"[epilepsy, protection money, secret love, mone...","A small-time hood must choose from among love,...",Drama Crime
4065,364083,Mi America,"[Drama, Crime]",0.0,0,0.039007,"[new york state, hate crime]",A hate-crime has been committed in a the small...,Drama Crime
1464,310706,Black Water Transit,"[Drama, Crime]",0.0,0,0.126738,[],In this action thriller set in post-Katrina Ne...,Drama Crime
2731,240,The Godfather: Part II,"[Drama, Crime]",8.3,3338,105.792936,"[italo-american, cuba, vororte, melancholy, pr...",In the continuing saga of the Corleone crime f...,Drama Crime
3887,627,Trainspotting,"[Drama, Crime]",7.8,2655,63.513324,"[london england, alcohol, sex, based on novel,...","Renton, deeply immersed in the Edinburgh drug ...",Drama Crime
892,524,Casino,"[Drama, Crime]",7.8,1307,40.066880,"[poker, drug abuse, 1970s, overdose, illegal p...",The life of the gambling paradise – Las Vegas ...,Drama Crime
1881,278,The Shawshank Redemption,"[Drama, Crime]",8.5,8205,136.747729,"[prison, corruption, police brutality, prison ...",Framed in the 1940s for the double murder of h...,Drama Crime
1370,8065,21,"[Drama, Crime]",6.5,1375,45.149948,"[gambling, card game, professor, harvard unive...","Ben Campbell is a young, highly intelligent, s...",Drama Crime
3378,14112,Auto Focus,"[Drama, Crime]",6.1,56,7.051521,"[male nudity, adultery, based on novel, infide...","A successful TV star during the 1960s, former ...",Drama Crime

In [108]:
similar_movies = find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather',10)
similar_movies[['title', 'vote_average']]

[[1663 1243 4065 1464 2731 3887  892 1881 1370 3378]]

                            title  vote_average
1663  Once Upon a Time in America           8.2
1243                 Mean Streets           7.2
4065                   Mi America           0.0
1464          Black Water Transit           0.0
2731       The Godfather: Part II           8.3
3887                Trainspotting           7.8
892                        Casino           7.8
1881     The Shawshank Redemption           8.5
1370                           21           6.5
3378                   Auto Focus           6.1

In [87]:
a=movies_df[movies_df['title'] == 'The Godfather']
a.index.values

array([3337], dtype=int64)

In [110]:
movies_df[['title','vote_average','vote_count']].sort_values('vote_average',ascending=False)[:10]

                         title  vote_average  vote_count
3519          Stiff Upper Lips          10.0           1
4247     Me You and Five Bucks          10.0           2
4045     Dancer, Texas Pop. 81          10.0           1
4662            Little Big Top          10.0           1
3992                 Sardaarji           9.5           2
2386            One Man's Hero           9.3           2
2970        There Goes My Baby           8.5           2
1881  The Shawshank Redemption           8.5        8205
2796     The Prisoner of Zenda           8.4          11
3337             The Godfather           8.4        5893

평가횟수에 대한 가중치가 부여된 평점방식

# 아이템 기반 최근접 이웃 협업 필터링 실습
- cosine similarity

In [215]:
import pandas as pd
import numpy as np
movies=pd.read_csv('./ml-latest-small/movies.csv')
ratings=pd.read_csv('./ml-latest-small/ratings.csv')
print(movies.shape)
print(ratings.shape)

(9742, 3)
(100836, 4)

In [216]:
movies.head(5)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [217]:
ratings.head(5)

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [218]:
# 모든 사용자를 row로 모든 영화를 column으로 구성한 데이터 세트로 변경해야함
ratings_matrix=ratings.pivot_table('rating',index='userId',columns='movieId')

In [219]:
ratings_movies=pd.merge(ratings,movies,on='movieId')
ratings_matrix=ratings_movies.pivot_table('rating',index='userId',columns='title')
ratings_matrix=ratings_matrix.fillna(0)

In [220]:
ratings_matrix.head(5)

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

- cosine_similaritiy() : 기준행과 비교행의 코사인 유사도를 행렬형태로 반환하는 함수
- 영화 간 유사도를 산출하기 위해서 행렬 전환필요

In [221]:
ratings_matrix_T=ratings_matrix.transpose()
ratings_matrix_T.head(3)

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
'Hellboy': The Seeds of Creation (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Round Midnight (1986),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [222]:
# 영화의 코사인 유사도 구하기
from sklearn.metrics.pairwise import cosine_similarity

In [223]:
item_sim=cosine_similarity(ratings_matrix_T,ratings_matrix_T)
item_sim

array([[1.        , 0.        , 0.        , ..., 0.32732684, 0.        ,
        0.        ],
       [0.        , 1.        , 0.70710678, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.70710678, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.32732684, 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [224]:
# cosine_similarity()로 반환된 넘파이 행렬을 영화명을 매핑해 DataFrame으로 변환
item_sim_df=pd.DataFrame(data=item_sim,index=ratings_matrix.columns,columns=ratings_matrix.columns)
item_sim_df.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),1.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.141653,0.0,...,0.0,0.342055,0.543305,0.707107,0.0,0.0,0.139431,0.327327,0.0,0.0
'Hellboy': The Seeds of Creation (2004),0.0,1.000000,0.707107,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0
'Round Midnight (1986),0.0,0.707107,1.000000,0.000000,0.000000,0.0,0.176777,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0
'Salem's Lot (2004),0.0,0.000000,0.000000,1.000000,0.857493,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0
'Til There Was You (1997),0.0,0.000000,0.000000,0.857493,1.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0

In [225]:
item_sim_df['Godfather, The (1972)'].sort_values(ascending=False)[:6]

title
Godfather, The (1972)                        1.000000
Godfather: Part II, The (1974)               0.821773
Goodfellas (1990)                            0.664841
One Flew Over the Cuckoo's Nest (1975)       0.620536
Star Wars: Episode IV - A New Hope (1977)    0.595317
Fargo (1996)                                 0.588614
Name: Godfather, The (1972), dtype: float64

In [226]:
item_sim_df['Inception (2010)'].sort_values(ascending=False)[1:6]

title
Dark Knight, The (2008)          0.727263
Inglourious Basterds (2009)      0.646103
Shutter Island (2010)            0.617736
Dark Knight Rises, The (2012)    0.617504
Fight Club (1999)                0.615417
Name: Inception (2010), dtype: float64

- 아이템 기반 유사도 데이터는 사용자의 평점 정보를 모두 취합해 영화에 따라 유사한 다른 영화를 추천할 수 있게 해줍니다.
- 이번에는 이 아이템 기반 유사도 데이터를 이용해 개인에게 특화된 영화추천 알고리즘 만들어보기
- 개인화된 영화 추천의 가장 큰 특징은 개인이 아직 관람하지 않은 영화를 추천한다는 것이다.
- 아직 관림하지 않은 영화에 대해서 아이템 유사도와 기존에 관람한 영화의 평점 데이터를 기반으로 해 새롭게 모든 영화의 예측 평점을 계산한 후 높은 예측 평점을 가진 영화를 추천

- Ru,n=사용자u의 아이템i와 가장 유사도가 높은 Top-N개 아이템에 대한 실제 평점벡터
- Su,n=아이템i와 가장 유사도가 높은 Top-N개 아이템의 유사도 벡터
- sum(Su,n * Ru,n) / sum(|Su,n|) = 사용자 u, 아이템 i의 개인화된 예측 평점값

In [227]:
def predict_rating(ratings_arr,item_sim_arr):
    ratings_pred=ratings_arr.dot(item_sim_arr)/np.array(np.abs(item_sim_arr).sum(axis=1))
    return ratings_pred

In [228]:
ratings_pred=predict_rating(ratings_matrix.values,item_sim_df.values)

In [229]:
ratings_pred_matrix=pd.DataFrame(ratings_pred,index=ratings_matrix.index,columns=ratings_matrix.columns)

In [230]:
ratings_pred_matrix

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.070345,0.577855,0.321696,0.227055,0.206958,0.194615,0.249883,0.102542,0.157084,0.178197,...,0.113608,0.181738,0.133962,0.128574,0.006179,0.212070,0.192921,0.136024,0.292955,0.720347
2,0.018260,0.042744,0.018861,0.000000,0.000000,0.035995,0.013413,0.002314,0.032213,0.014863,...,0.015640,0.020855,0.020119,0.015745,0.049983,0.014876,0.021616,0.024528,0.017563,0.000000
3,0.011884,0.030279,0.064437,0.003762,0.003749,0.002722,0.014625,0.002085,0.005666,0.006272,...,0.006923,0.011665,0.011800,0.012225,0.000000,0.008194,0.007017,0.009229,0.010420,0.084501
4,0.049145,0.277628,0.160448,0.206892,0.309632,0.042337,0.130048,0.116442,0.099785,0.097432,...,0.051269,0.076051,0.055563,0.054137,0.008343,0.159242,0.100941,0.062253,0.146054,0.231187
5,0.007278,0.066951,0.041879,0.013880,0.024842,0.018240,0.026405,0.018673,0.021591,0.018841,...,0.009689,0.022246,0.013360,0.012378,0.000000,0.025839,0.023712,0.018012,0.028133,0.052315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.246832,1.293006,0.752661,0.935924,1.032354,0.407038,0.516819,0.594590,0.489913,0.408661,...,0.227092,0.405114,0.291452,0.276143,0.055006,0.636525,0.510522,0.346652,0.550174,0.893777
607,0.052248,0.305255,0.180669,0.218834,0.179443,0.115288,0.165817,0.075548,0.104890,0.109500,...,0.059516,0.135763,0.093843,0.086643,0.003707,0.144222,0.134705,0.107674,0.156614,0.576894
608,0.324435,1.022541,0.598467,0.425468,0.349562,0.494081,0.529903,0.227746,0.480980,0.442384,...,0.276586,0.594918,0.457094,0.444436,0.038681,0.616733,0.717768,0.538586,0.527639,0.698871
609,0.004835,0.053593,0.026251,0.000000,0.002827,0.015528,0.017849,0.007791,0.013172,0.014981,...,0.006575,0.014368,0.010334,0.007742,0.000000,0.018070,0.015600,0.013108,0.018328,0.033377
610,3.628303,1.517918,0.833668,0.399443,0.310888,1.117761,0.567028,0.226168,1.053823,0.564894,...,0.441868,1.933069,2.588550,2.573509,0.553681,0.628323,1.083299,1.816091,0.565075,0.574654

In [231]:
def get_mse(pred,actual):
    pred=pred[actual.nonzero()].flatten()
    actual=actual[actual.nonzero()].flatten()
    return mean_squared_error(pred,actual)

In [232]:
print('아이템 기반 모든 최근접 이웃 MSE: ',get_mse(ratings_pred,ratings_matrix.values))

아이템 기반 모든 최근접 이웃 MSE:  9.895354759094706

In [233]:
item_sim_df

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.141653,0.000000,...,0.000000,0.342055,0.543305,0.707107,0.0,0.000000,0.139431,0.327327,0.000000,0.0
'Hellboy': The Seeds of Creation (2004),0.000000,1.000000,0.707107,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
'Round Midnight (1986),0.000000,0.707107,1.000000,0.000000,0.000000,0.0,0.176777,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
'Salem's Lot (2004),0.000000,0.000000,0.000000,1.000000,0.857493,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
'Til There Was You (1997),0.000000,0.000000,0.000000,0.857493,1.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.211467,0.216295,0.097935,0.132489,...,0.000000,0.000000,0.000000,0.000000,0.0,1.000000,0.192259,0.000000,0.170341,0.0
xXx (2002),0.139431,0.000000,0.000000,0.000000,0.000000,0.0,0.089634,0.000000,0.276512,0.019862,...,0.069716,0.305535,0.173151,0.246482,0.0,0.192259,1.000000,0.270034,0.100396,0.0
xXx: State of the Union (2005),0.327327,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.156764,0.000000,...,0.000000,0.382543,0.177838,0.231455,0.0,0.000000,0.270034,1.000000,0.000000,0.0
¡Three Amigos! (1986),0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.372876,0.180009,0.169385,0.249586,...,0.180009,0.000000,0.000000,0.000000,0.0,0.170341,0.100396,0.000000,1.000000,0.0
À nous la liberté (Freedom for Us) (1931),0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.0

In [234]:
ratings_matrix

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.5,3.5,0.0,0.0,0.0
609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,...,0.0,4.0,3.5,3.0,0.0,0.0,2.0,1.5,0.0,0.0

In [235]:
ratings_pred_matrix

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.070345,0.577855,0.321696,0.227055,0.206958,0.194615,0.249883,0.102542,0.157084,0.178197,...,0.113608,0.181738,0.133962,0.128574,0.006179,0.212070,0.192921,0.136024,0.292955,0.720347
2,0.018260,0.042744,0.018861,0.000000,0.000000,0.035995,0.013413,0.002314,0.032213,0.014863,...,0.015640,0.020855,0.020119,0.015745,0.049983,0.014876,0.021616,0.024528,0.017563,0.000000
3,0.011884,0.030279,0.064437,0.003762,0.003749,0.002722,0.014625,0.002085,0.005666,0.006272,...,0.006923,0.011665,0.011800,0.012225,0.000000,0.008194,0.007017,0.009229,0.010420,0.084501
4,0.049145,0.277628,0.160448,0.206892,0.309632,0.042337,0.130048,0.116442,0.099785,0.097432,...,0.051269,0.076051,0.055563,0.054137,0.008343,0.159242,0.100941,0.062253,0.146054,0.231187
5,0.007278,0.066951,0.041879,0.013880,0.024842,0.018240,0.026405,0.018673,0.021591,0.018841,...,0.009689,0.022246,0.013360,0.012378,0.000000,0.025839,0.023712,0.018012,0.028133,0.052315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.246832,1.293006,0.752661,0.935924,1.032354,0.407038,0.516819,0.594590,0.489913,0.408661,...,0.227092,0.405114,0.291452,0.276143,0.055006,0.636525,0.510522,0.346652,0.550174,0.893777
607,0.052248,0.305255,0.180669,0.218834,0.179443,0.115288,0.165817,0.075548,0.104890,0.109500,...,0.059516,0.135763,0.093843,0.086643,0.003707,0.144222,0.134705,0.107674,0.156614,0.576894
608,0.324435,1.022541,0.598467,0.425468,0.349562,0.494081,0.529903,0.227746,0.480980,0.442384,...,0.276586,0.594918,0.457094,0.444436,0.038681,0.616733,0.717768,0.538586,0.527639,0.698871
609,0.004835,0.053593,0.026251,0.000000,0.002827,0.015528,0.017849,0.007791,0.013172,0.014981,...,0.006575,0.014368,0.010334,0.007742,0.000000,0.018070,0.015600,0.013108,0.018328,0.033377
610,3.628303,1.517918,0.833668,0.399443,0.310888,1.117761,0.567028,0.226168,1.053823,0.564894,...,0.441868,1.933069,2.588550,2.573509,0.553681,0.628323,1.083299,1.816091,0.565075,0.574654

In [236]:
[np.argsort(item_sim[:,1])[:-21:-1]]

[array([   1, 5773, 7888,  362, 3913,   11,    2, 4688, 7362, 3411, 8735,
        4430, 3532,  863, 4161, 2340, 9625, 9061, 4639, 9096], dtype=int64)]

In [237]:
# 특정 영화와 가장 비슷한 유사도를 가지는 여화에 대해서만 유사도 벡터를 적용하는 함수
def predict_rating_topsim(ratings_arr,item_sim_arr,n=20):
    #사용자 아이템 평점 행렬 크기만큼 0으로 채운 행렬 초기화
    pred=np.zeros(ratings_arr.shape)
    
    #사용자-아이템 평점 행렬의 열 크기만큼 루프 수행
    for col in range(ratings_arr.shape[1]):
        # 유사도 행렬에서 유사도가 큰 순으로 n개 데이터 행렬의 인덱스 반환
        top_n_items=[np.argsort(item_sim_arr[:,col])[:-n-1:-1]]
        # 개인화된 예측 평점을 계산
        for row in range(ratings_arr.shape[0]):
            pred[row,col]=item_sim_arr[col,:][top_n_items].dot(ratings_arr[row,:][top_n_items].T)
            pred[row,col]/=np.sum(np.abs(item_sim_arr[col,:][top_n_items]))
    return pred

In [254]:
ratings_pred=predict_rating_topsim(ratings_matrix.values,item_sim_df.values,n=20)
print('아이템 기반 최근점 Top-20 이웃 MSE:',get_mse(ratings_pred,ratings_matrix.values))

# 계산된 예측 평점 데이터는 DataFrame으로 재생성
ratings_pred_matrix = pd.DataFrame(data=ratings_pred, index= ratings_matrix.index,
                                   columns = ratings_matrix.columns)

<ipython-input-237-d9a44e71b81e>:12: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  pred[row,col]=item_sim_arr[col,:][top_n_items].dot(ratings_arr[row,:][top_n_items].T)
<ipython-input-237-d9a44e71b81e>:13: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  pred[row,col]/=np.sum(np.abs(item_sim_arr[col,:][top_n_items]))

아이템 기반 최근점 Top-20 이웃 MSE: 3.6949999176225483

In [255]:
user_rating_id = ratings_matrix.loc[9, :]
user_rating_id[ user_rating_id > 0].sort_values(ascending=False)[:10]

title
Adaptation (2002)                                                                 5.0
Austin Powers in Goldmember (2002)                                                5.0
Lord of the Rings: The Fellowship of the Ring, The (2001)                         5.0
Lord of the Rings: The Two Towers, The (2002)                                     5.0
Producers, The (1968)                                                             5.0
Citizen Kane (1941)                                                               5.0
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    5.0
Back to the Future (1985)                                                         5.0
Glengarry Glen Ross (1992)                                                        4.0
Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)                                     4.0
Name: 9, dtype: float64

In [256]:
# 사용자가 이미 평점을 준 영화를 제외하고  추천헤야 함
def get_unseen_movies(rating_matrix,userId):
    #  userID로 입력받은 사용자의 모든 영화 정보를 추출해 Series로 반환함
    # 반환된 user_rating은 영화명을 인덱스로 가지는 Series
    user_rating = rating_matrix.loc[userId,:]
    
    # 기존에 관람한 영화의 인덱스를 추출해 list객체로 만든다.
    already_seen=user_rating[user_rating>0].index.tolist()
    
    #모든 영화명을 list 객체로 만듦.
    movie_list=rating_matrix.columns.tolist()
    
    # already_seen에 해당하는 영화는 movie_list에서 제외함
    unseen_list=[movie for movie in movie_list if movie not in already_seen]
    
    return unseen_list

In [257]:
def recommend_movie_by_userid(pred_df,userId,unseen_list,top_n=10):
    recomm_movies=pred_df.loc[userId,unseen_list].sort_values(ascending=False)[:top_n]
    return recomm_movies

unseen_list=get_unseen_movies(ratings_matrix,9)
recomm_movies=recommend_movie_by_userid(ratings_pred_matrix,9,unseen_list,top_n=10)
recomm_movies=pd.DataFrame(recomm_movies.values,recomm_movies.index,columns=['pred_socre'])
recomm_movies

                                                    pred_socre
title
Shrek (2001)                                          0.866202
Spider-Man (2002)                                     0.857854
Last Samurai, The (2003)                              0.817473
Indiana Jones and the Temple of Doom (1984)           0.816626
Matrix Reloaded, The (2003)                           0.800990
Harry Potter and the Sorcerer's Stone (a.k.a. H...    0.765159
Gladiator (2000)                                      0.740956
Matrix, The (1999)                                    0.732693
Pirates of the Caribbean: The Curse of the Blac...    0.689591
Lord of the Rings: The Return of the King, The ...    0.676711

# 행렬 분해를 이용한 잠재 요인 협업 필터링 실습
- SGD 기반 행렬분해 구현
- R : 원본사용자 - 아이템 평점행렬
- K : 잠재요인의 차원 수

In [325]:
from sklearn.metrics import mean_squared_error
def get_rmse(R,P,Q,non_zeros):
    error=0
    full_pred_matrix=np.dot(P,Q.T)
    
    x_non_zero_ind=[non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind=[non_zero[1] for non_zero in non_zeros]
    R_non_zeros=R[x_non_zero_ind,y_non_zero_ind]
    full_pred_matrix_non_zeros=full_pred_matrix[x_non_zero_ind,y_non_zero_ind]
    
    mse=mean_squared_error(R_non_zeros,full_pred_matrix_non_zeros)
    rmse=np.sqrt(mse)
    return rmse

In [326]:
def matrix_factorization(R,K,steps=200,learning_rate=0.01,r_lambda=0.01):
    num_users,num_items=R.shape
    # P,Q매트릭스의 크기를 지정하고 정규분포를 가진 랜덤한 값으로 입력
    np.random.seed(1)
    #본 예제에서는 random 정규분포의 표준편차가 작지 않으면 무한대로 수렴하는 경우가 발생할 수 있어서 1/K를 적용
    P=np.random.normal(scale=1./K,size=(num_users,K))
    Q=np.random.normal(scale=1./K,size=(num_items,K))
    
    
    break_count=0
    
    # R>0 인 행 위치, 열 위치, 값을 non_zeros리스트 객체에 저장
    non_zeros = [ (i, j, R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j] > 0 ]
   
    # SGD기법으로 P,Q매트릭스 계속 업데이트
    for step in range(steps):
        for i, j, r in non_zeros:
            eij=r-np.dot(P[i,:],Q[j,:].T)
            P[i,:] = P[i,:] + learning_rate*(eij * Q[j, :] - r_lambda*P[i,:])
            Q[j,:] = Q[j,:] + learning_rate*(eij * P[i, :] - r_lambda*Q[j,:])
        
        rmse=get_rmse(R ,P, Q, non_zeros)
        if (step%10)==0:
            print('### iteration step: ',step,'rmse: ',rmse)
    return P,Q

In [327]:
import pandas as pd
import numpy as np
movies=pd.read_csv('./ml-latest-small/movies.csv')
ratings=pd.read_csv('./ml-latest-small/ratings.csv')
ratings = ratings[['userId', 'movieId', 'rating']]
#ratings_matrix=ratings.pivot_table('rating',index='userId',columns='movieId')

In [328]:
# title 컬럼을 얻기 이해 movies 와 조인 수행
rating_movies = pd.merge(ratings, movies, on='movieId')

# columns='title' 로 title 컬럼으로 pivot 수행. 
ratings_matrix = rating_movies.pivot_table('rating', index='userId', columns='title')

In [329]:
P,Q=matrix_factorization(ratings_matrix.values,K=50,steps=200,learning_rate=0.01,r_lambda=0.01)
pred_matrix=np.dot(P,Q.T)

### iteration step :  0  rmse :  2.9023619751336867
### iteration step :  10  rmse :  0.7335768591017927
### iteration step :  20  rmse :  0.5115539026853442
### iteration step :  30  rmse :  0.37261628282537446
### iteration step :  40  rmse :  0.2960818299181014
### iteration step :  50  rmse :  0.2520353192341642
### iteration step :  60  rmse :  0.22487503275269854
### iteration step :  70  rmse :  0.2068545530233154
### iteration step :  80  rmse :  0.19413418783028688
### iteration step :  90  rmse :  0.18470082002720406
### iteration step :  100  rmse :  0.17742927527209104
### iteration step :  110  rmse :  0.1716522696470749
### iteration step :  120  rmse :  0.16695181946871723
### iteration step :  130  rmse :  0.16305292191997542
### iteration step :  140  rmse :  0.15976691929679646
### iteration step :  150  rmse :  0.1569598699945732
### iteration step :  160  rmse :  0.1545339818671543
### iteration step :  170  rmse :  0.15241618551077643
### iteration step :  180  rmse :  0.1505508073962831
### iteration step :  190  rmse :  0.14889470913232092

In [353]:
ratings_pred_matrix=pd.DataFrame(data=pred_matrix,index=ratings_matrix.index,columns=ratings_matrix.columns)

In [354]:
ratings_pred_matrix

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,3.055084,4.092018,3.564130,4.502167,3.981215,1.271694,3.603274,2.333266,5.091749,3.972454,...,1.402608,4.208382,3.705957,2.720514,2.787331,3.475076,3.253458,2.161087,4.010495,0.859474
2,3.170119,3.657992,3.308707,4.166521,4.311890,1.275469,4.237972,1.900366,3.392859,3.647421,...,0.973811,3.528264,3.361532,2.672535,2.404456,4.232789,2.911602,1.634576,4.135735,0.725684
3,2.307073,1.658853,1.443538,2.208859,2.229486,0.780760,1.997043,0.924908,2.970700,2.551446,...,0.520354,1.709494,2.281596,1.782833,1.635173,1.323276,2.887580,1.042618,2.293890,0.396941
4,2.628629,3.035550,2.575746,3.706912,3.430636,0.706441,3.330280,1.978826,4.560368,2.775710,...,1.046116,2.912178,2.479592,2.231915,1.888629,2.211364,0.645603,1.585734,3.542892,0.591540
5,2.116148,3.084761,2.747679,3.783490,3.946990,0.883259,1.958953,1.757317,2.054312,2.775258,...,0.956159,3.893975,2.717024,2.002443,2.053337,3.983639,2.099626,1.423718,2.490428,0.531403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,3.153469,3.536398,3.128222,3.875599,3.821362,1.010045,2.284450,2.287194,4.148796,3.487517,...,1.105429,3.647394,3.342759,2.446343,2.406133,3.613071,1.849264,1.526109,2.860815,0.673099
607,2.502048,3.577547,3.095692,4.081789,4.038996,1.095224,3.698198,1.904581,5.347442,3.114650,...,0.963407,3.230442,3.526719,2.084052,2.119598,4.135631,3.124109,2.362195,3.421672,0.758574
608,2.154503,3.019060,2.679379,3.567550,3.483444,0.909505,2.387003,1.644313,3.090541,3.197815,...,0.818661,3.372644,2.936734,2.049884,2.097775,4.452331,3.504461,1.906708,2.419560,0.701739
609,2.566479,3.285659,2.910122,3.717481,3.665580,1.036884,2.908776,1.844237,2.868990,3.175409,...,1.003584,3.033540,2.943151,2.173251,2.234396,3.839926,2.520343,1.603675,2.970382,0.636880
610,3.951789,3.549175,3.156069,4.050809,4.001964,1.206514,3.086769,2.383306,3.426834,3.763558,...,1.223902,3.977474,3.464065,2.972646,2.538213,4.019379,2.012463,1.528829,4.119260,0.751230

In [355]:
ratings_matrix

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.5,3.5,NaN,NaN,NaN
609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,...,NaN,4.0,3.5,3.0,NaN,NaN,2.0,1.5,NaN,NaN

In [357]:
def get_unseen_movies(ratings_matrix,userId):
    user_rating=ratings_matrix.loc[userId,:]
    already_seen=user_rating[user_rating>0].index.tolist()
    
    titles=ratings_matrix.columns.tolist()
    unseen_list=[title for title in titles if title not in already_seen]
    return unseen_list

In [358]:
def recomm_movies_by_userId(pred_df,userId,unseen_list,top_n=10):
    recomm_movies=pred_df.loc[userId,unseen_list].sort_values(ascending=False)[:top_n]
    return recomm_movies

In [359]:
unseen_list=get_unseen_movies(ratings_matrix,9)
recomm_movies=recomm_movies_by_userId(ratings_pred_matrix,9,unseen_list,top_n=10)
recomm_movies

title
Rear Window (1954)                                       5.704612
South Park: Bigger, Longer and Uncut (1999)              5.451100
Rounders (1998)                                          5.298393
Blade Runner (1982)                                      5.244951
Roger & Me (1989)                                        5.191962
Gattaca (1997)                                           5.183179
Ben-Hur (1959)                                           5.130463
Rosencrantz and Guildenstern Are Dead (1990)             5.087375
Big Lebowski, The (1998)                                 5.038690
Star Wars: Episode V - The Empire Strikes Back (1980)    4.989601
Name: 9, dtype: float64

In [361]:
pd.DataFrame(recomm_movies.values,index=recomm_movies.index,columns=['pred_score'])

                                                    pred_score
title
Rear Window (1954)                                    5.704612
South Park: Bigger, Longer and Uncut (1999)           5.451100
Rounders (1998)                                       5.298393
Blade Runner (1982)                                   5.244951
Roger & Me (1989)                                     5.191962
Gattaca (1997)                                        5.183179
Ben-Hur (1959)                                        5.130463
Rosencrantz and Guildenstern Are Dead (1990)          5.087375
Big Lebowski, The (1998)                              5.038690
Star Wars: Episode V - The Empire Strikes Back ...    4.989601